#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
CONFIG_DIR="$CONFIG_HOME/esp12-sender"
ENV_FILE="$CONFIG_DIR/sender.env"
SERVICE_DIR="$CONFIG_HOME/systemd/user"
SERVICE_NAME="esp12-sender.service"
SERVICE_FILE="$SERVICE_DIR/$SERVICE_NAME"
COMPOSE_ENV_FILE="$SCRIPT_DIR/.docker.env"
PYTHON_BIN="$SCRIPT_DIR/.venv/bin/python"
SENDER_ENTRY="$SCRIPT_DIR/sender_v2.py"

usage() {
    cat <<'EOF'
Usage: ./senderctl.sh <command>

Commands:
  setup               Interactive setup wizard (creates ~/.config/esp12-sender/sender.env)
  write-compose-env   Sync docker env file from saved config
  run                 Run sender using saved config
  compose-up          Build and start docker compose service (recommended)
  compose-down        Stop and remove docker compose service
  compose-restart     Restart docker compose service
  compose-status      Show docker compose container status
  compose-logs        Tail docker compose logs
  ensure-docker-boot  Enable docker daemon at boot (requires sudo)
  install-service     Install and start user-level systemd service
  uninstall-service   Stop and remove user-level systemd service
  start               Start installed service
  stop                Stop installed service
  restart             Restart installed service
  status              Show service status
  logs                Tail service logs
  quickstart          setup + install-service
  quickstart-compose  setup + compose-up

Examples:
  ./senderctl.sh quickstart-compose
  ./senderctl.sh quickstart
  ./senderctl.sh status
EOF
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"
}

compose_cmd() {
    if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
        echo "docker compose"
        return
    fi
    if command -v docker-compose >/dev/null 2>&1; then
        echo "docker-compose"
        return
    fi
    die "Docker Compose not found. Install Docker Desktop / docker compose plugin."
}

prompt_value() {
    local label="$1"
    local default="$2"
    local secret="${3:-0}"
    local input=""

    if [[ "$secret" == "1" ]]; then
        if [[ -n "$default" ]]; then
            read -r -s -p "$label [********]: " input
        else
            read -r -s -p "$label: " input
        fi
        echo
    else
        read -r -p "$label [$default]: " input
    fi

    if [[ -z "$input" ]]; then
        printf '%s' "$default"
    else
        printf '%s' "$input"
    fi
}

load_existing_env_defaults() {
    if [[ -f "$ENV_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$ENV_FILE"
    fi
}

write_env_file() {
    local mqtt_host="$1"
    local mqtt_port="$2"
    local mqtt_user="$3"
    local mqtt_pass="$4"
    local sender_hostname="$5"
    local send_interval_sec="$6"
    local mqtt_qos="$7"

    mkdir -p "$CONFIG_DIR"
    {
        echo "# Auto-generated by senderctl.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        printf 'MQTT_HOST=%q\n' "$mqtt_host"
        printf 'MQTT_PORT=%q\n' "$mqtt_port"
        printf 'MQTT_USER=%q\n' "$mqtt_user"
        printf 'MQTT_PASS=%q\n' "$mqtt_pass"
        printf 'SENDER_HOSTNAME=%q\n' "$sender_hostname"
        printf 'SEND_INTERVAL_SEC=%q\n' "$send_interval_sec"
        printf 'MQTT_QOS=%q\n' "$mqtt_qos"
    } >"$ENV_FILE"
    chmod 600 "$ENV_FILE"
}

ensure_runtime_ready() {
    [[ -f "$SENDER_ENTRY" ]] || die "Missing sender entrypoint: $SENDER_ENTRY"
    if [[ -x "$PYTHON_BIN" ]]; then
        return
    fi
    need_cmd uv
    echo "Setting up Python runtime (first run only)..."
    (cd "$SCRIPT_DIR" && uv sync)
}

setup_wizard() {
    [[ -t 0 ]] || die "setup requires an interactive terminal"

    load_existing_env_defaults

    local mqtt_host="${MQTT_HOST:-127.0.0.1}"
    local mqtt_port="${MQTT_PORT:-1883}"
    local mqtt_user="${MQTT_USER:-}"
    local mqtt_pass="${MQTT_PASS:-}"
    local sender_hostname="${SENDER_HOSTNAME:-$(hostname)}"
    local send_interval_sec="${SEND_INTERVAL_SEC:-1.0}"
    local mqtt_qos="${MQTT_QOS:-0}"

    echo "ESP12 Sender setup wizard"
    echo "Press Enter to keep defaults."
    mqtt_host="$(prompt_value "MQTT host" "$mqtt_host")"
    mqtt_port="$(prompt_value "MQTT port" "$mqtt_port")"
    mqtt_user="$(prompt_value "MQTT username (leave blank if not required)" "$mqtt_user")"
    mqtt_pass="$(prompt_value "MQTT password" "$mqtt_pass" "1")"
    sender_hostname="$(prompt_value "Sender hostname (shown on ESP)" "$sender_hostname")"
    send_interval_sec="$(prompt_value "Send interval seconds" "$send_interval_sec")"
    mqtt_qos="$(prompt_value "MQTT QoS (0-2)" "$mqtt_qos")"

    [[ "$mqtt_port" =~ ^[0-9]+$ ]] || die "MQTT port must be a number"
    [[ "$mqtt_qos" =~ ^[0-2]$ ]] || die "MQTT QoS must be 0, 1 or 2"

    write_env_file "$mqtt_host" "$mqtt_port" "$mqtt_user" "$mqtt_pass" "$sender_hostname" "$send_interval_sec" "$mqtt_qos"
    ensure_runtime_ready
    echo "Saved config: $ENV_FILE"
}

load_env_or_die() {
    [[ -f "$ENV_FILE" ]] || die "Config not found: $ENV_FILE (run: ./senderctl.sh setup)"
    # shellcheck disable=SC1090
    set -a
    source "$ENV_FILE"
    set +a
    [[ -n "${MQTT_HOST:-}" ]] || die "MQTT_HOST is empty in $ENV_FILE"
}

write_compose_env() {
    load_env_or_die
    {
        echo "# Auto-generated by senderctl.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "MQTT_HOST=${MQTT_HOST}"
        echo "MQTT_PORT=${MQTT_PORT}"
        echo "MQTT_USER=${MQTT_USER:-}"
        echo "MQTT_PASS=${MQTT_PASS:-}"
        echo "SENDER_HOSTNAME=${SENDER_HOSTNAME:-$(hostname)}"
        echo "SEND_INTERVAL_SEC=${SEND_INTERVAL_SEC:-1.0}"
        echo "MQTT_QOS=${MQTT_QOS:-0}"
        echo "DRM_CLASS_ROOT=/sys/class/drm"
    } >"$COMPOSE_ENV_FILE"
    chmod 600 "$COMPOSE_ENV_FILE"
    echo "Wrote compose env: $COMPOSE_ENV_FILE"
}

run_sender() {
    ensure_runtime_ready
    load_env_or_die
    cd "$SCRIPT_DIR"
    exec "$PYTHON_BIN" "$SENDER_ENTRY"
}

need_docker_runtime() {
    need_cmd docker
    docker info >/dev/null 2>&1 || die "Docker daemon is not running"
}

compose_up() {
    if [[ ! -f "$ENV_FILE" ]]; then
        setup_wizard
    fi
    need_docker_runtime
    local ccmd
    ccmd="$(compose_cmd)"
    write_compose_env
    cd "$SCRIPT_DIR"
    if [[ "$ccmd" == "docker compose" ]]; then
        docker compose up -d --build
    else
        docker-compose up -d --build
    fi
    echo "Compose service is up (restart policy: unless-stopped)."
}

compose_down() {
    need_docker_runtime
    local ccmd
    ccmd="$(compose_cmd)"
    cd "$SCRIPT_DIR"
    if [[ "$ccmd" == "docker compose" ]]; then
        docker compose down
    else
        docker-compose down
    fi
}

compose_restart() {
    need_docker_runtime
    local ccmd
    ccmd="$(compose_cmd)"
    cd "$SCRIPT_DIR"
    if [[ "$ccmd" == "docker compose" ]]; then
        docker compose restart
    else
        docker-compose restart
    fi
}

compose_status() {
    need_docker_runtime
    local ccmd
    ccmd="$(compose_cmd)"
    cd "$SCRIPT_DIR"
    if [[ "$ccmd" == "docker compose" ]]; then
        docker compose ps
    else
        docker-compose ps
    fi
}

compose_logs() {
    need_docker_runtime
    local ccmd
    ccmd="$(compose_cmd)"
    cd "$SCRIPT_DIR"
    if [[ "$ccmd" == "docker compose" ]]; then
        exec docker compose logs -f --tail=200
    else
        exec docker-compose logs -f --tail=200
    fi
}

ensure_docker_boot() {
    need_cmd sudo
    need_cmd systemctl
    sudo systemctl enable --now docker
    echo "Docker service enabled at boot."
}

need_systemd_user() {
    need_cmd systemctl
    systemctl --user show-environment >/dev/null 2>&1 || die "systemd --user is unavailable in this session"
}

install_service() {
    if [[ ! -f "$ENV_FILE" ]]; then
        setup_wizard
    fi
    ensure_runtime_ready
    need_systemd_user

    mkdir -p "$SERVICE_DIR"
    cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=ESP12 Metrics Sender
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$SCRIPT_DIR
ExecStart=/usr/bin/env bash $SCRIPT_DIR/senderctl.sh run
Restart=always
RestartSec=3
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=default.target
EOF

    systemctl --user daemon-reload
    systemctl --user enable --now "$SERVICE_NAME"
    echo "Installed and started: $SERVICE_NAME"
    if command -v loginctl >/dev/null 2>&1; then
        if ! loginctl show-user "$USER" -p Linger 2>/dev/null | grep -q '=yes'; then
            echo "Tip: run 'sudo loginctl enable-linger $USER' to keep service running after logout."
        fi
    fi
}

uninstall_service() {
    need_systemd_user
    systemctl --user disable --now "$SERVICE_NAME" >/dev/null 2>&1 || true
    rm -f "$SERVICE_FILE"
    systemctl --user daemon-reload
    echo "Removed service: $SERVICE_NAME"
}

service_start() {
    need_systemd_user
    systemctl --user start "$SERVICE_NAME"
}

service_stop() {
    need_systemd_user
    systemctl --user stop "$SERVICE_NAME"
}

service_restart() {
    need_systemd_user
    systemctl --user restart "$SERVICE_NAME"
}

service_status() {
    need_systemd_user
    systemctl --user --no-pager status "$SERVICE_NAME"
}

service_logs() {
    need_systemd_user
    exec journalctl --user -u "$SERVICE_NAME" -f --no-pager
}

quickstart() {
    setup_wizard
    install_service
}

quickstart_compose() {
    setup_wizard
    compose_up
    echo "If needed, run: ./senderctl.sh ensure-docker-boot"
}

main() {
    local cmd="${1:-}"
    case "$cmd" in
    setup)
        setup_wizard
        ;;
    write-compose-env)
        write_compose_env
        ;;
    run)
        run_sender
        ;;
    compose-up)
        compose_up
        ;;
    compose-down)
        compose_down
        ;;
    compose-restart)
        compose_restart
        ;;
    compose-status)
        compose_status
        ;;
    compose-logs)
        compose_logs
        ;;
    ensure-docker-boot)
        ensure_docker_boot
        ;;
    install-service)
        install_service
        ;;
    uninstall-service)
        uninstall_service
        ;;
    start)
        service_start
        ;;
    stop)
        service_stop
        ;;
    restart)
        service_restart
        ;;
    status)
        service_status
        ;;
    logs)
        service_logs
        ;;
    quickstart)
        quickstart
        ;;
    quickstart-compose)
        quickstart_compose
        ;;
    *)
        usage
        [[ -n "$cmd" ]] && exit 1
        ;;
    esac
}

main "${1:-}"
